<?php

namespace DeSmart\Adr\Action;

use DeSmart\Adr\Responder\ResponderInterface;

/**
 * If the action (controller) returns an instance of ResponderInterface
 * return the response generated by it.
 */
trait ReturnsResponderTrait
{
    /**
     * @param string $method
     * @param array $parameters
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function callAction($method, $parameters)
    {
        $response = call_user_func_array([$this, $method], $parameters);

        if (true === $response instanceof ResponderInterface) {
            return $response->respond();
        }

        return $response;
    }
}
